name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      pattern:
        image: ghcr.io/backsoul/patterns:latest
        ports:
          - 8000:8000
      test:
        image: ghcr.io/backsoul/patterns:latest
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install jq
        run: sudo apt-get -y install jq

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          docker exec test go test -v ./tests
