name: Docker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          dockerfile: Dockerfile
          context: .

      - name: Log in to Docker registry
        run: docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/backsoul/patterns:latest

      - name: Run tests in the 'test' service container
        run: docker-compose run --rm test go test ./...
