name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          dockerfile: Dockerfile
          context: .

      - name: Log in to Docker registry
        run: docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/backsoul/patterns:latest

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install jq
        run: sudo apt-get -y install jq

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          docker run ghcr.io/backsoul/patterns:latest go test -v ./tests
