name: Go Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Run tests and generate coverage report
        run: go test -coverprofile=coverage.out ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.out

      - name: Generate Coverage Badge
        run: |
          COVERAGE_BADGE_URL="URL_DEL_BADGE_QUE_COPIASTE_DE_BADGEN"
          curl -s https://github.com/backsoul/patterns/blob/branch/coverage.out > coverage-badge.svg
        env:
          COVERAGE_BADGE_URL: https://github.com/backsoul/patterns/blob/branch/coverage.out

      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: coverage-badge.svg
