name: Go Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Run tests and generate coverage report
        run: go test -coverprofile=coverage.out ./...

      - name: generate an image
        run: |
          set -x
          total=`go tool cover -func=coverage.out | grep total: | grep -Eo '[0-9]+\.[0-9]+'`
          if (( $(echo "$total <= 50" | bc -l) )) ; then
              COLOR=red
          elif (( $(echo "$total > 80" | bc -l) )); then
              COLOR=green
          else
              COLOR=orange
          fi

          git fetch
          git checkout badge -f
          git pull
          git merge origin/main  
          curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > badge.svg
          git add .
          git commit -m "added badge"
          git push
