name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install jq
        run: sudo apt-get -y install jq

      - name: Install gocov and gocov-xml
        run: |
          go get -u github.com/axw/gocov/gocov
          go get -u github.com/AlekSi/gocov-xml

      - name: Build
        run: go build -v ./...

      - name: Test and Generate Coverage Report
        run: |
          go test -v ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out > coverage.txt
          go tool cover -html=coverage.out -o coverage.html
          gocov convert coverage.out | gocov-xml > coverage.xml
        shell: bash

      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: |
            coverage.txt
            coverage.html
            coverage.xml
